[build]
  publish = "dist"
  command = "npm run build && cp src/business.json dist/ && cp -r src/favicons dist/"

[[redirects]]
  from = "/hussainwebdesigns"
  to = "https://g.page/r/CS5wD9WoN4olEAI/review"
  status = 301
  force = true

[[redirects]]
  from = "/stwerburghsfoodwine"
  to = "https://search.google.com/local/writereview?placeid=ChIJWzdfNBSOcUgRiih81qlD43w"
  status = 301
  force = true

[[redirects]]
  from = "/absolutemustard"
  to = "https://www.google.com/search?q=Absolute+Mustard,+Swindon&ludocid=1208571025746344190#lrd=0x81b35ec64975d553:0x10da1d47cfc1038e,3"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200